### ISSUE TITLE
variables, objects, arrays 

### ISSUE THREAD

**Issue by groupbcra** [groupbcra/Star-Wars-Responsive-JQuery-Game#5]
Document Load {
call function  startScreen();
}

var  fighterObj {
obi-wan:  health Power
luke:  health power

// This is where we store all the fighters

}
var fighterHealth =  fighterObj.chosenFighter.Health
var fighterPower =  fighterObj.chosenFighter.Power

var  enemyObj {
darthS: health power
darth
// This is where we store all the fighters
}

function startScreen{
window.empty();
Load gameSetup();
}

**Comment by coffeewhistle** [comment]
Compared to the example provided in the class instructions, I think I'm done with the layout and design. Changes have been pushed to var-obj-arr-#5 branch.

@avidavis - can you give me some quick feedback on what I'm missing or other things I should be thinking about/adding?

**Comment by coffeewhistle** [comment]
Added javascript objects and some console.log tests to show that they're pulling properly.
